#pragma once

#include "CoreMinimal.h"
#include "PlayerMeshData.generated.h"

class USkeletalMesh;

USTRUCT(BlueprintType)
struct FAutogeneratedMeshData
{
	GENERATED_BODY()
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Mesh Data")
	TSoftObjectPtr<USkeletalMesh> Torso{};

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Mesh Data")
	TSoftObjectPtr<USkeletalMesh> Top{};
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Mesh Data")
	TSoftObjectPtr<USkeletalMesh> LegLeft{};

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Mesh Data")
	TSoftObjectPtr<USkeletalMesh> LegRight{};

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Mesh Data")
	TSoftObjectPtr<USkeletalMesh> Hair{};

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Mesh Data")
	TSoftObjectPtr<USkeletalMesh> Shoes{};

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Mesh Data")
	TSoftObjectPtr<USkeletalMesh> ArmLeft{};

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Mesh Data")
	TSoftObjectPtr<USkeletalMesh> ArmRight{};
};
USTRUCT(BlueprintType)
struct FPlayerMeshData
{
	GENERATED_BODY()

	UPROPERTY(BlueprintReadOnly, Category = "Mesh Data")
	TObjectPtr<USkeletalMesh> MergedMesh{};
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Mesh Data")
	TSoftObjectPtr<USkeletalMesh> Base{};

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Mesh Data")
	FAutogeneratedMeshData Components{};
};